#include "test.h"

UNIT_TEST_GENERATE_FUNC(ASSERT_ok){
    UT_BEG();
    UT_ASSERT(0 == 0);
    UT_END();
}
UNIT_TEST_GENERATE_FUNC(ASSERT_er){
    UT_BEG();
    UT_ASSERT(0 == 1);
    UT_END();
}
UNIT_TEST_GENERATE_FUNC(ASSERT_TRUE_ok){
    UT_BEG();
    UT_ASSERT_TRUE(true);
    UT_END();
}
UNIT_TEST_GENERATE_FUNC(ASSERT_TRUE_er){
    UT_BEG();
    UT_ASSERT_TRUE(false);
    UT_END();
}
UNIT_TEST_GENERATE_FUNC(ASSERT_FALSE_ok){
    UT_BEG();
    UT_ASSERT_FALSE(false);
    UT_END();
}
UNIT_TEST_GENERATE_FUNC(ASSERT_FALSE_er){
    UT_BEG();
    UT_ASSERT_FALSE(true);
    UT_END();
}
UNIT_TEST_GENERATE_FUNC(ASSERT_EQUAL_ok){
    UT_BEG();
    UT_ASSERT_EQUAL(5, 5);
    UT_END();
}
UNIT_TEST_GENERATE_FUNC(ASSERT_EQUAL_er){
    UT_BEG();
    UT_ASSERT_EQUAL(5, 6);
    UT_END();
}
UNIT_TEST_GENERATE_FUNC(ASSERT_NOT_EQUAL_ok){
    UT_BEG();
    UT_ASSERT_NOT_EQUAL(8, 9);
    UT_END();
}
UNIT_TEST_GENERATE_FUNC(ASSERT_NOT_EQUAL_er){
    UT_BEG();
    UT_ASSERT_NOT_EQUAL(8, 8);
    UT_END();
}
UNIT_TEST_GENERATE_FUNC(ASSERT_PTR_EQUAL_ok){
    UT_BEG();
    int a = 0;
    int *b = &a;
    UT_ASSERT_PTR_EQUAL(&a, b);
    UT_END();
}
UNIT_TEST_GENERATE_FUNC(ASSERT_PTR_EQUAL_er){
    UT_BEG();
    int a = 0;
    int *b = &a;
    UT_ASSERT_PTR_EQUAL(&a, &b);
    UT_END();
}
UNIT_TEST_GENERATE_FUNC(ASSERT_PTR_NOT_EQUAL_ok){
    UT_BEG();
    int a = 0;
    int *b = &a;
    UT_ASSERT_PTR_NOT_EQUAL(&a, &b);
    UT_END();
}
UNIT_TEST_GENERATE_FUNC(ASSERT_PTR_NOT_EQUAL_er){
    UT_BEG();
    int a = 0;
    int *b = &a;
    UT_ASSERT_PTR_NOT_EQUAL(&a, b);
    UT_END();
}
UNIT_TEST_GENERATE_FUNC(ASSERT_PTR_NULL_ok){
    UT_BEG();
    UT_ASSERT_PTR_NULL(NULL);
    UT_END();
}
UNIT_TEST_GENERATE_FUNC(ASSERT_PTR_NULL_er){
    UT_BEG();
    int *b = NULL;
    UT_ASSERT_PTR_NULL(b + 1);
    UT_END();
}
UNIT_TEST_GENERATE_FUNC(ASSERT_PTR_NOT_NULL_ok){
    UT_BEG();
    int *b = NULL;
    UT_ASSERT_PTR_NOT_NULL(b + 1);
    UT_END();
}
UNIT_TEST_GENERATE_FUNC(ASSERT_PTR_NOT_NULL_er){
    UT_BEG();
    UT_ASSERT_PTR_NOT_NULL(NULL);
    UT_END();
}
UNIT_TEST_GENERATE_FUNC(ASSERT_STRING_EQUAL_ok){
    UT_BEG();
    UT_ASSERT_STRING_EQUAL("test1", "test1");
    UT_END();
}
UNIT_TEST_GENERATE_FUNC(ASSERT_STRING_EQUAL_er){
    UT_BEG();
    UT_ASSERT_STRING_EQUAL("test1", "test2");
    UT_END();
}
UNIT_TEST_GENERATE_FUNC(ASSERT_STRING_NOT_EQUAL_ok){
    UT_BEG();
    UT_ASSERT_STRING_NOT_EQUAL("test1", "test2");
    UT_END();
}
UNIT_TEST_GENERATE_FUNC(ASSERT_STRING_NOT_EQUAL_er){
    UT_BEG();
    UT_ASSERT_STRING_NOT_EQUAL("test1", "test1");
    UT_END();
}
UNIT_TEST_GENERATE_FUNC(ASSERT_NSTRING_EQUAL_ok){
    UT_BEG();
    UT_ASSERT_NSTRING_EQUAL("test1", "test1", 5);
    UT_END();
}
UNIT_TEST_GENERATE_FUNC(ASSERT_NSTRING_EQUAL_er){
    UT_BEG();
    UT_ASSERT_NSTRING_EQUAL("test1", "test2", 5);
    UT_END();
}
UNIT_TEST_GENERATE_FUNC(ASSERT_NSTRING_NOT_EQUAL_ok){
    UT_BEG();
    UT_ASSERT_NSTRING_NOT_EQUAL("test1", "test2", 5);
    UT_END();
}
UNIT_TEST_GENERATE_FUNC(ASSERT_NSTRING_NOT_EQUAL_er){
    UT_BEG();
    UT_ASSERT_NSTRING_NOT_EQUAL("test1", "test1", 5);
    UT_END();
}
UNIT_TEST_GENERATE_FUNC(ASSERT_DOUBLE_EQUAL_ok){
    UT_BEG();
    UT_ASSERT_DOUBLE_EQUAL(3.00, 3.01, 0.1);
    UT_END();
}
UNIT_TEST_GENERATE_FUNC(ASSERT_DOUBLE_EQUAL_er){
    UT_BEG();
    UT_ASSERT_DOUBLE_EQUAL(3.00, 3.01, 0.001);
    UT_END();
}
UNIT_TEST_GENERATE_FUNC(ASSERT_DOUBLE_NOT_EQUAL_ok){
    UT_BEG();
    UT_ASSERT_DOUBLE_NOT_EQUAL(3.00, 3.01, 0.001);
    UT_END();
}
UNIT_TEST_GENERATE_FUNC(ASSERT_DOUBLE_NOT_EQUAL_er){
    UT_BEG();
    UT_ASSERT_DOUBLE_NOT_EQUAL(3.00, 3.01, 0.1);
    UT_END();
}
